# Generated by Django 5.0.6 on 2024-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_of_work', models.DateTimeField(null=True)),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
